SUTT/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('', include('landingpage.urls')),
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),

]

landingpage/urls.py
from django.urls import path
from . import views  
urlpatterns = [
    path('', views.home, name ='home')
]

polls/urls.py
from django.urls import path
from . import views
app_name = 'polls'
urlpatterns = [
    path('', views.home, name='home'),
    path('<int:question_id>/', views.detail, name='detail'),
    path('<int:question_id>/results/', views.results, name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

landingpage/models.py
from django.db import models

# Create your models here.

polls/models.py
from django.db import models
import datetime
from django.db import models
from django.utils import timezone
class Question(models.Model):
    question_text = models.CharField(max_length=255)
    pub_date = models.DateTimeField('Date Published')
    def __str__(self):
        return self.question_text
    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)
class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=255)
    votes = models.IntegerField(default=0)
    def __str__(self):
        return self.choice_text

landingpage/views.py
from django.shortcuts import render
from django.template import loader
def home(request):
    return render(request,'landingpage/home.html')

polls/views.py
from django.shortcuts import render
from django.template import loader
from django.http import HttpResponse,HttpResponseRedirect
from polls.models import Choice, Question
from django.urls import reverse
def home(request):
    latest_question_list = Question.objects.order_by('-pub_date')[:5]
    template = loader.get_template('polls/home.html')
    context = {
        'latest_question_list': latest_question_list,
    }
    return render(request, 'polls/home.html', context)
def detail(request, question_id):
    try:
        question = Question.objects.get(pk=question_id)
    except Question.DoesNotExist:
        raise Http404("Question does not exist")
    return render(request, 'polls/detail.html', {'question': question})
def results(request, question_id):
    question = Question.objects.get(pk = question_id)
    return render(request, 'polls/results.html', {'question': question})
def vote(request, question_id):
    try:
        question = Question.objects.get(pk=question_id)
    except Question.DoesNotExist:
        raise Http404("Question does not exist")
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

polls/templates/landingpage/home.html
<html lang="en-US">
<head>
<meta charset="utf-8" />
<title>Home Page</title>
</head>
<body>
<div class ="card text-center">
    <div class ="card-body">
        <h1>Welcome To Polls APP</h1>
          
<p>This is a Django polling app</p>
  
        <a class ="btn btn-dark" href ="{% url 'polls:home' %}">
            View Available Polls</a>
    </div>
</div>
</body>
</html>

polls/templates/polls/detail.html
<html lang="en-US">
<head>
<meta charset="utf-8" />
<title>Home Page</title>
</head>
<body>
<a class ="btn btn-secondary btn-sm mb-3" href ="{% url 'polls:home' %}">Back To Polls</a>
<h1 class ="text-center mb-3">{{ question.question_text }}</h1>
  
{% if error_message %}
<p class ="alert alert-danger">
    <strong>{{ error_message }}</strong>
</p>
  
{% endif %}
  
<form action ="{% url 'polls:vote' question.id %}" method ="post">
    {% csrf_token %}
    {% for choice in question.choice_set.all %}
    <div class ="form-check">
        <input type ="radio" name ="choice" class ="form-check-input" id ="choice{{ forloop.counter }}"
            value ="{{ choice.id }}" />
        <label for ="choice{{ forloop.counter }}">{{ choice.choice_text }}</label>
    </div>
    {% endfor %}
    <input type ="submit" value ="Vote" class ="btn btn-success btn-lg btn-block mt-4" />
</form>
</body>
</html>

polls/templates/polls/home.html
<html lang="en-US">
<head>
<meta charset="utf-8" />
<title>Home Page</title>
</head>
<body>
<h1 class ="text-center mb-3">Poll Questions</h1>
{% if latest_question_list %}
{% for question in latest_question_list %}
<div class ="card-mb-3">
    <div class ="card-body">
        <p class ="lead">{{ question.question_text }}</p>  
        <a href ="{% url 'polls:detail' question.id %}" class ="btn btn-primary btn-sm">Vote Now</a>
        <a href ="{% url 'polls:results' question.id %}" class ="btn btn-secondary btn-sm">Results</a>
    </div>
</div>
{% endfor %}
{% else %}
<p>No polls available</p>
{% endif %}
</body>
</html>

polls/templates/polls/results.html
<html lang="en-US">
<head>
<meta charset="utf-8" />
<title>Home Page</title>
</head>
<body>
<h1 class ="mb-5 text-center">{{ question.question_text }}</h1>
  
<ul class ="list-group mb-5">
    {% for choice in question.choice_set.all %}
    <li class ="list-group-item">
        {{ choice.choice_text }} <span class ="badge badge-success float-right">{{ choice.votes }}
            vote{{ choice.votes | pluralize }}</span>
    </li>
    {% endfor %}
</ul>
  
<a class ="btn btn-secondary" href ="{% url 'polls:home' %}">Back To Polls</a>
<a class ="btn btn-dark" href ="{% url 'polls:detail' question.id %}">Vote again?</a>
</body>
</html>